/* eslint-disable prettier/prettier */
import React, {Component} from 'react';
import {View, Text, ScrollView} from 'react-native';

//3rd Party Libraries
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import Icon from 'react-native-vector-icons/Ionicons';

//Custom External StyleSheet
// import {styles, textInput, buttonStyles} from '../../styles';

//Custom Components
import SecondaryHeader from '../components/SecondaryHeader';

class PrivacyPolicyScreen extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View>
        <SecondaryHeader secondaryHeaderTitle="Privacy Policy" />
        <View style={{flexDirection:'row'}}>
          <View style={{flex:0.5}} />
          <View style={{flex:8, flexDirection:'column'}}>
          <ScrollView>
            <Text>
            Privacy Policy
            </Text><Text>
“The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.”
</Text><Text>
Realyze recognises the value of your privacy and appreciates your trust with us. The usage of Realyze, its products, services, affiliations to any related third-party tools within the scope of its affiliations with Realyze, including but not limited to Task Management, and Authorisation requires and takes into account, your agreement to the collection, usage and disclosure of the information, as explained and stated in this Privacy Policy, in accordance with the applicable laws of India and concerned user’s geographical countries laws. This applies to current and former visitors to our website, our app and our affiliated products.
</Text><Text>
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
</Text><Text>
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Realyze, all its subdomains and extensions linked, its app, services and products.
</Text><Text>
The products and services offered by Realyze, its website, app or any affiliated offering are owned and operated by Yash Atreya, an Indian citizen, residing at C-304, Karachi Citizens Society, Juhu Versova Link Road, Andheri West, Mumbai - 400053, India. 
</Text><Text>
For the purpose of this policy, wherever the context so requires,
</Text><Text>
1.	The term ‘You’ & ‘User’ shall mean any legal person or entity accessing or using the services or offerings provided on Realyze’s App, Website or any affiliated offerings.
2.	The term ‘company’ refers to the collective of app/ website or any other platform in the context of Realyze, that Mr Yash Atreya and the team/ persons affiliated to him owns/ operates.
3.	The terms ‘We’, ‘Us’ & ‘Our’ shall mean the App and/or the Website, as the context so requires.
4.	That ‘Platform’ shall refer to the offerings of Realyze, like the app, website or any other platform that the company owns/ operates.
5.	The terms ‘Party’ & ‘Parties’ shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires.
6.	The headings of each section in this Policy are only for the purpose of organizing the various provisions under this Policy in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.
7.	The use of the website or app by the user is solely governed by this Policy (Privacy Policy), Refund and Cancellation Policy and the ‘Terms and Conditions’ of the website, and any modifications or amendments made thereto by the company from time to time, at its sole discretion. 
Consent
</Text><Text>
By using the website/ app, the user consents to the acceptance of this policy and the mentioned terms unless the user explicitly denies providing the consent. As for the terms, 
</Text><Text>
1.	The User unequivocally agrees that this Policy and the aforementioned Terms constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into the Terms, and shall be treated as part and parcel of the same. 
2.	The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User and that User's act of visiting any part of the Website constitutes the User’s full and final acceptance of the Policy and the aforementioned Terms.
3.	The user agrees for secondary purposes, including but not limited to marketing and communication, when providing us information.
4.	The user is aware that the public information user puts, both on the offline and online mediums, directed towards the company, directly or indirectly, including but not limited to message boards, forums etc. are stored by the company and any such information may be used to resolve and pursue disputes in the requisite jurisdictions.
5.	The user is aware that the terms are binding, but are not limiting in nature of information collection. The user is aware that the company can collect information outside the scope of this policy, provided that the company asks the user’s consent for the same.
6.	The user has the right to deny or withdraw their consent of providing us with any information, at any time, by contacting us at +919820453014 or emailing us at our operating address: C-304 Karachi Citizens Society, Juhu Versova Link Road, Andheri West, Mumbai - 400053, India.
</Text><Text>
Information we collect:
</Text><Text>
The user, when visiting the app or any affiliated website, expressly agrees and acknowledges that the company collects and stores the information that either the user provides explicitly or the company collects using the third-party tools and platform affiliations.
</Text><Text>
The company, with its offerings, either as an app or website, collects the data mentioned hereafter. We read your emails and access your phone storage. THE COMPANY DO NOT STORE ANY OF YOUR SENSITIVE INFORMATION ON ITS SERVERS.
</Text><Text>
Log Data
</Text><Text>
1.	That the company collects and stores the information when the user visits its platforms in the form of log data on the company servers. 
2.	This log data may include information including but not limited to IP address, login details and your other statistics including access time, pages viewed and site/ services you use before/ after interacting with the platform.
Information User provides to us:
1.	The company collects the information provided directly by the user, in the form of creation or modification of the account, uploading details or communicating otherwise with the company in form of direct or indirect contact with the company offerings.
2.	The information may include the user’s name, email, contact details, address, pictures, payment methods, any particular notes, or any documents provided explicitly by the user.
3.	The information extends to retrieving OTP to sign up the user, using Gmail OAuth to authorise and link the email with the Platform.
4.	The user might provide some input on the platform in the form of text messages, voice messages, location information, files and media articles/ links.
5.	The user might use and choose to share his contact addresses with the platform, in order to communicate/ receive communication. 
6.	The company may also receive information from other sources that the user interacts with on our platform and it’s extended presence.
Information we collect through extended use of platform’s services:
</Text><Text>
The company’s platform fetches the data from user’s devices and related information, once provided with the consent of the user, explicitly for some of the device data as Mobile Platforms (Android, iOS etc) have laid out in their terms of service. The company might ask the user for the following information, for which the permissions are based on the mobile platform’s policies.
</Text><Text>
1.	Personal Information: The company stores the details such as your personal identification details, the documents you explicitly upload on our platform in the form of service usage or communication, direct with our company. However, sensitive personal information of the user IS NOT STORED ON OU SERVERS.
2.	Contact Information: The platform accesses your contact addresses if provided permission. This is used to store contact information from your address book to facilitate our services.
3.	Device Information: The company may collect information about your device, its IP address, operating systems and versions, language, Filename and types, Unique Device Identifiers and Mobile Network providers.
4.	Document Information: The document we fetch from your emails will not be stored on our servers and only be used for indexing on the native device.
5.	Cookies: The platform use cookies to operate and provide services, understand user preferences and customise services accordingly.
</Text><Text>
What we do with the information:
</Text><Text>
The company collects the information and uses it to facilitate its services. We use this information to facilitate the service and promote a user’s experience. The company states:
</Text><Text>
1.	That the information collected is used to improve its platform, generate insights and statistics for the fulfilment of the platform and its services.
2.	That the information might be used for communicating with the user, directly or indirectly in the form of feedback, marketing and promotional emails, grievance redressal or any as company deem fit. The user can opt-out of these communications anytime by explicitly directly communicating with the company.
3.	Perform internal operations, to prevent fraud and abuse of our Services; to troubleshoot software bugs and operational problems; to conduct data analysis, testing, and research; and to monitor and analyze usage and activity trends;
4.	Personalize and improve the Services, including to provide or recommend features and content.
Security:
</Text><Text>
We value the trust you place in us regarding your information and usage of our products and services. Any information entered by the user on the website, app and its affiliated subdomains and extensions is stored confidentially to protect the user against unintentional disclosure to third parties. Every usage of the user’s data is notified to the user prior to the action taken by the company.
</Text><Text>
In order to protect your personal information, we take reasonable precautions and follow the industry’s best practices. We do our best to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed. However, no method of security is completely reliable and secure, and the company or any of its affiliates are not responsible in case of including but not limited to data theft, security loopholes, and information mismanagement.
</Text><Text>
Third-Party Services
</Text><Text>
The company might engage with third parties to provide the user additional features and to facilitate service delivery to the user. The services might include links to other sites.
</Text><Text>
The engage might include facilitation of the company’s services, perform service-related services, analysing the data provided and assisting the company’s platform capabilities.
</Text><Text>
In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us. If the user clicks on a third-party link, it’ll be directed to another site.
For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
</Text><Text>
In particular, remember that certain providers may be located in or have facilities that are located in a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.
</Text><Text>
Disclosure of personal information
</Text><Text>
The company do not sell or share any personally identifiable information to any third party (public/private), except under the conditions as mentioned above. We do, however, share the information to third parties to deliver the services requested by you. However, we may disclose your personal information if we are required by law to do so or if you violate our Terms of Service or if you give us your consent to do so. 
As for the terms of the privacy policy,
</Text><Text>
1.	The user is aware that the company may share the User’s personal information with other entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website’s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.
2.	The User is aware that the company may disclose personal information if required to do so by law or if the platform/ company in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. 
3.	The User is further aware that the Website/Company and its affiliates may share some or all of the User’s personal information with other business entities should the Company/Website (or its assets) plan to merge with, or be acquired by such business entity, or in the event of reorganization, amalgamation, or restructuring of the Company’s business. Such a business entity or new entity will continue to be bound by the Terms and Policy, as may be amended from time to time.
</Text><Text>
Changes to the policy
</Text><Text>
The company retains the sole and exclusive rights to amend or modify the Policy and the aforementioned Terms without any prior permission or intimation to the user and the user expressly agrees that any such modifications and updates shall come into effect immediately. The user is required to review it frequently to avoid any conflict of interest.
</Text><Text>
However, if we make any material or substantial changes, we will place a prominent notice on our website/ application. If the change materially affects the user, we will send a notice to you by email.

            </Text>
            <View style={{marginBottom: 150}} />
          </ScrollView>
          </View>
          <View style={{flex:0.5}} />
        </View>
      </View>
    );
  }
}

export default PrivacyPolicyScreen;
